### PR TITLE
Support Windows & simplify api

### LINKED ISSUE #2: Windows support

### PR DESCRIPTION
**Pull request by VandeurenGlenn**
closes #2

### CODE REVIEW

**Comment by RyanAfrish7** [comment]
Hey! Thanks for the PR. I will merge it within a couple days.

**Comment by VandeurenGlenn** [comment]
Hi, your welcome, no pressure, always open for critics/suggestions.

**Comment by tobeorla** [comment]
"I will merge it within a couple days." - 28 Jun :(

**Comment by arjndr** [comment]
image

**Comment by RyanAfrish7** [comment]
@arjndr :nerd_face:

**Pull request merged**
